server:
  port: 8002

spring:
  application:
    name: consumer
    env: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: nacos
        ip: 127.0.0.1



